### ISSUE TITLE
Some X11 fonts are not found (sometimes)

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub-linux-builders#14]
```
Error: processing vignette '<--->' failed with diagnostics:
X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 2 at size 11 could not be loaded
Execution halted
```

**Comment by markvanderloo** [comment]
Hi Gabor, have you found any clue to this issue? I just ran into it on a freshly build R-devel on my Ubuntu 16.04 box. All works fine with `rhub::check_with_devel` and the recent R-release (locally). I'm now skipping building vignettes, but that's a bit of an ugly workaround.

**Comment by maelle** [comment]
Same issue in https://github.com/r-hub/rhub/issues/188

**Comment by gaborcsardi** [comment]
Fedora, Ubuntu and Debian images have more X11 fonts now (once deployed in a couple of minutes). Hopefully this is enough.
