### ISSUE TITLE
OpenSUSE

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-linux-builders#16]
Check on OpenSUSE with stock R from [zypper ](https://cran.r-project.org/bin/linux/suse/README.html). Suse uses rpm and the package names mostly match those of Fedora (few small exceptions).

**Comment by gaborcsardi** [comment]
So if it is almost the same, what is the benefit? :)

**Comment by jeroen** [comment]
The OS and software is very different :-) Only the package _names_ are similar as Fedora, e.g.  `openssl-devel` is also called `openssl-devel` in Suse.

**Comment by gaborcsardi** [comment]
PRs are welcome. Please reopen if you want to submit one.
