### ISSUE TITLE
CentOS 6.4

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-linux-builders#18]
By default, CentOS automatically updates to the latest point release. However some clusters decide to stick with a point release. See e.g. [this example](https://github.com/jeroenooms/openssl/issues/29). In particular CentOS 6.4 is not uncommon. 

This version of CentOS has really old packages (even older than CentOS 6.x). Nobody in their right mind would use this but apparently some supercomputers are frozen on that. I'll see if I can put together a docker image to test on this OS.

**Comment by gaborcsardi** [comment]
Please reopen if you still want to do this.
