### ISSUE TITLE
libgeos++-dev and udunits missing

### ISSUE THREAD

**Issue by edzer** [r-hub/rhub-linux-builders#20]
When compiling [sf](http://github.com/edzer/sfr) (another R consortium funded project) I noticed that it breaks on geos++ headers not being available; this would be libgeos++-dev on ubuntu/debian systems. It was added around a month ago on my request to the [CRAN list](http://statmath.wu.ac.at/AASC/debian/) and is listed [here](http://statmath.wu.ac.at/AASC/debian/binary-amd64/Packages). Do you sync with rcheckserver?

Another thing I noticed is missing is libudunits2-dev and udunits, both are on rcheckserver.

**Comment by gaborcsardi** [comment]
r-hub does not have a set of preinstalled OS packages. Instead, it looks at the `SystemRequirements` field in `DESCRIPTION`, and tries to preinstall everything that is specified there. This is what it does for GDAL and GEOS:
```
{
  "gdal": {
    "sysreqs": "GDAL binaries",
    "platforms": {
      "DEB": "gdal-bin",
      "OSX/brew": "gdal",
      "RPM": "gdal"
    }
  }
}
```

```
{
  "libgeos": {
    "sysreqs": "/\\bGEOS\\b/",
    "platforms": {
      "DEB": "libgeos-dev",
      "OSX/brew": "geos",
      "RPM": "geos-devel"
    }
  }
}
```

So GDAL is not detected properly, I'll fix that in a sec.

I am having a hard time building a source package for `sfr` on macOS, because brew only as old gdal. Can you please attach a source R package here, so that I can try it.

**Comment by gaborcsardi** [comment]
OK, fixed GDAL: 

```
{
  "gdal": {
    "sysreqs": "/\\bGDAL\\b/",
    "platforms": {
      "DEB": "gdal-bin",
      "OSX/brew": "gdal",
      "RPM": "gdal"
    }
  }
}
```

I tested on a source package without the vignettes, I can build that on macOS, and it seems OK:
https://builder.r-hub.io/status/sf_0.2-4.tar.gz-92e8ccd26ffd4a9c83ea69cc50966c90

Please re-open if you have problems.

**Comment by edzer** [comment]
Thanks, Gabor, looking good!

**Comment by noamross** [comment]
I believe I have a related problem building a [package](https://github.com/ecohealthalliance/fasterize) that depends on **sf**.  It does not build successfully on r-hub Ubuntu, though it does on Windows and linux under Travis.  sf fails to install properly and I get the error "Package required but not available: ‘sf’"

https://builder.r-hub.io/status/fasterize_0.1.0.tar.gz-ffffa388398844409832edf7bc8ac716

Successful Windows build: https://builder.r-hub.io/status/fasterize_0.1.0.tar.gz-c2cd68aaaba14d11a3279d8fc21df49f
Travis build: https://travis-ci.org/ecohealthalliance/fasterize/jobs/212841749
Attempt with putting GDAL, GEOS, PROJ in my own package SystemRequirements:  https://builder.r-hub.io/status/fasterize_0.1.0.tar.gz-8996442b264741108d03b0ccd228258f

**Comment by joelgombin** [comment]
Same problem here, for https://github.com/joelgombin/concaveman (works OK in travis-ci and winbuilder): https://builder.r-hub.io/status/concaveman_1.0.tar.gz-578f36e62587462da97fef447236cd9b#L1013

**Comment by edzer** [comment]
FYI: `sf` no longer requires libgeos++-dev, but only libgeos-dev, see e.g. [here](https://github.com/r-spatial/sf/blob/master/.travis.yml).

**Comment by joelgombin** [comment]
My issues seem to be more gdal-related at the moment, as far as I can tell.
