### ISSUE TITLE
automake and libtool

### ISSUE THREAD

**Issue by rundel** [r-hub/rhub-linux-builders#21]
It looks like the debian containers have automake and libtool available but they are missing from the ubuntu, fedora and centos containers. 

Any chance of adding them for the sake of uniformity?

**Comment by gaborcsardi** [comment]
What would you use automake and libtool for?

I suggest that if you need them, then declare them as SystemRequirements, and I can add them to the system requirements database.

**Comment by rundel** [comment]
I'm playing around with wrapping a system library into an R package using the nloptr model of downloading and building a static version of the library during package configuration, just happens that the library wants libtool / automake.

SystemRequirements seems like a good solution, my confusion came from initially testing with the debian images which worked and then getting a failure on the other linux images.
