### ISSUE TITLE
r-devel is old

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-linux-builders#23]
Just tested some packages with `check_with_rdevel()` but when I inspected the log files it says:

```
R Under development (unstable) (2016-10-30 r71610) -- "Unsuffered Consequences"
```

Is that expected?

**Comment by gaborcsardi** [comment]
No, it is not. The Docker images did update ~ 6 days ago (they update every Sunday), but seemingly, R was not recompiled. 

I just updated all images manually, and will run the updates with `docker build --no-cache` now.

**Comment by jeroen** [comment]
Thanks!
