### ISSUE TITLE
sf no longer compiling because of missing gdal 2.0

### ISSUE THREAD

**Issue by edzer** [r-hub/rhub-linux-builders#24]
See e.g. https://builder.r-hub.io/status/sf_0.5-3.tar.gz-3fe6276b76344c54a92dea161f54836f

This used to work; several reverse dependencies experience the same problem, see #20 

To make this work on ubuntu, add ppa:ubuntugis/ubuntugis-unstable, see e.g. [here](https://builder.r-hub.io/status/sf_0.5-3.tar.gz-3fe6276b76344c54a92dea161f54836f)

**Comment by ateucher** [comment]
This is happening for me as well on a couple of packages. I am happy to try a PR, but wondering if that should be here, or in [sysreqsdb](https://github.com/r-hub/sysreqsdb/blob/master/platforms/linux-x86_64-ubuntu-gcc.json)?

**Comment by maelle** [comment]
is this still an issue?

**Comment by obrl-soil** [comment]
I think so @maelle - my package `slga` is [passing on travis](https://travis-ci.com/obrl-soil/slga) but [failing on r-hub](https://builder.r-hub.io/status/slga_1.0.1.tar.gz-be1bbca2d6e544b588ae8ca0488226af). `sf` won't install because "configure: error: gdal-config not found or not executable."

**Comment by maelle** [comment]
Thanks @obrl-soil! I think I got that error locally on Ubuntu, and installed packages using the first Google search link. :see_no_evil:  What do you experts recommend in such cases? 

@gaborcsardi the fix should happen in sysreqsdb I think?

**Comment by obrl-soil** [comment]
Kind of looks like gdal.json is used where libgdal.json should be?

**Comment by gaborcsardi** [comment]
The original issue is fixed in https://github.com/r-hub/sysreqsdb/commit/1a05909b74d3d061221710739fc9b28eadcbe376

**Comment by gaborcsardi** [comment]
rgeos does not compile, at least on our Debian, though, so still not at a happy place.

**Comment by maelle** [comment]
@gaborcsardi is https://stat.ethz.ch/pipermail/r-package-devel/2019q2/003799.html related to this?
