### ISSUE TITLE
ubuntu-clang images

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rhub-linux-builders#25]
In an attempt to replicate an error that occurs on Fedora + clang 5.0, I've built an Ubuntu image with clang 5.0. (I have found instructions on [installing clang 5.0 on Ubuntu](https://askubuntu.com/a/905211/30266) only.) Happy to prepare a PR if you think this is useful here.

**Comment by gaborcsardi** [comment]
IDK, to be honest. We already have a bunch of images, and there is some work with them. Do you think it offers something that others don't? Can't we just update the Fedora image?

**Comment by krlmlr** [comment]
I don't remember. I just think a Linux + clang image would be useful.

**Comment by gaborcsardi** [comment]
Agreed, but there is one already, with Fedora.

**Comment by krlmlr** [comment]
I vaguely remember that updating clang on Fedora looked more difficult than installing it on Ubuntu, but things might have changed.

**Comment by gaborcsardi** [comment]
This might very well be the case, I mean, about the updating on Fedora.....

**Comment by gaborcsardi** [comment]
Please submit a PR if you would like this. Thanks!

**Comment by krlmlr** [comment]
I still have it as an uncommitted change in my clone of this repo :-)

**Comment by gaborcsardi** [comment]
The Fedora images do have clang 5.0.1, actually.

**Comment by krlmlr** [comment]
This wasn't the case when I opened the issue. Do we still want Ubuntu with clang?

**Comment by gaborcsardi** [comment]
I dont mind, up to you.

**Comment by krlmlr** [comment]
Happy to. Some instructions suggest adding a PPA, but I just checked and it seems clang-5.0 is available from xenial-updates and can be installed from there. Do you prefer a PPA or the default repos?

**Comment by gaborcsardi** [comment]
Default is better imo.

**Comment by gaborcsardi** [comment]
Seems like we'll have a Debian with clang and ISO8859-15 char set like the new CRAN flavour: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/rcmdcheck-00check.html

So I'll close this.
