### ISSUE TITLE
For Ubuntu have parity with official R binaries for lapack and blas

### ISSUE THREAD

**Issue by jspiewak** [r-hub/rhub-linux-builders#27]
The official R binaries for Ubuntu are built against libatlas3 and therefore don't have libRlapack.so and libRblas.so

Packages built by r-hub that require lapack or blas therefore cannot be used with the official R binary.

**Comment by gaborcsardi** [comment]
Makes sense.

**Comment by gaborcsardi** [comment]
Sorry this is taking sooooo long. Do you have an example build script or Dockerfile that shows how the official binaries are built? Or is that somewhere in an Ubuntu dev repo on Launchpad?

**Comment by jspiewak** [comment]
I don't, I just consume the R builds from CRAN. Perhaps reach out to Dirk who I believe maintains those builds. Is there a reason you don't use them directly?

**Comment by gaborcsardi** [comment]
I guess the reason for our own build is more control. This way we can be sure what R version we are using, and the config is also more uniform across R versions.

But these are not very strong reasons, and there are arguments for using the "official" build as well. 

Let me try to change it.

**Comment by gaborcsardi** [comment]
I updated the Ubuntu builder, can you please try? It looks OK to me, so I'll also update the Debian one.

**Comment by gaborcsardi** [comment]
I updated the debian-release-gcc image as well.

**Comment by gaborcsardi** [comment]
This seems to work, so I'll close this issue. Please reopen if you have problems. Thanks.

**Comment by jspiewak** [comment]
My initial look yesterday was good. I haven't attempted to build a package that using liblapack or libblas yet, should get to it today or tomorrow.
