### ISSUE TITLE
r-hub build for Ubuntu broken

### ISSUE THREAD

**Issue by jspiewak** [r-hub/rhub-linux-builders#28]
![image](https://user-images.githubusercontent.com/399516/35751460-7d50ec96-080d-11e8-8b91-4845e8bb0809.png)

![image](https://user-images.githubusercontent.com/399516/35751466-88364476-080d-11e8-866f-adb1ccfe0264.png)

**Comment by gaborcsardi** [comment]
Ooops. It is good now, but there is a lot of backlog.
