### ISSUE TITLE
Add an MIT licence to this repo

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub-linux-builders#35]
+ info about the licence in the README?

If we link it to Docker hub, this way the licence would show up on all Docker hub repos.

**Comment by maelle** [comment]
rocker-org Dockerfiles have a license, "The Dockerfiles in this repository are licensed under the GPL 2 or later.".

What license should these Dockerfiles have?

**Comment by gaborcsardi** [comment]
The same, as some are derivatives.
