### ISSUE TITLE
Have a debian + clang + ISO8859-15 image, like on CRAN

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub-linux-builders#40]

**Comment by maelle** [comment]
cc @davidgohel

**Comment by gaborcsardi** [comment]
@maelle so I suppose that if I do this, we'll need to manually update the config on Docker Hub, right?

**Comment by gaborcsardi** [comment]
While at it, I'll also simplify the structure, i.e. have 
```
debian
debian-gcc
debian-clang
...
fedora
fedora-gcc
fedora-clang
...
```

This will be better for disk space.

**Comment by maelle** [comment]
You mean creating a new repo on Docker hub? Yes, this needs to be done manually.

**Comment by gaborcsardi** [comment]
This will be mostly fixed when the images are deployed, but still need to add the platform to the web app: https://github.com/r-hub/rhub-frontend/issues/36

**Comment by maelle** [comment]
Plus it'd be nice to trigger a rhub website build on travis bc the 2 vignettes list platforms.
