### ISSUE TITLE
Using Docker in R-Hub - section for Rockerverse paper

### ISSUE THREAD

**Issue by nuest** [r-hub/rhub-linux-builders#43]
:wave: Hi there! Would you be interested in contributing some experiences and reasoning (e.g. why not to use Rocker images only) on using Docker for running R-Hub in this article that is currently written?

https://github.com/nuest/rockerverse-paper

See also https://github.com/nuest/rockerverse-paper/issues/3 and https://github.com/nuest/rockerverse-paper/issues/8 (conference call later today)

**Comment by gaborcsardi** [comment]
> why not to use Rocker images only

* we have a lot more OSes and configs, so it makes sense to make them more uniform
* we wanted to have common upstream images, e.g. debian -> debian-gcc -> debian-gcc-devel
* we run as a regular user, so this needs a different config
* we have a lot more software, e.g. pandoc and a fairly complete LaTeX installation

**Comment by nuest** [comment]
Thanks for the input, makes sense!

I would probably add to the list

- we want environments that are close to what CRAN does/has
