### ISSUE TITLE
Question regarding release, patched, devel, and Fedora

### ISSUE THREAD

**Issue by ismailsunni** [r-hub/rhub-linux-builders#45]
Hello,

##  release, patched, devel, 
After I read the README, I got the impression that all docker images that have `release`, `devel`, `patched` in the name, have the R in its image. But, when I tried the `devel` and `patched` one, they don't have R inside it (I was expecting there are devel and patched version). I checked, that R is only available on the `release` one. Is there any reason behind it?

## Fedora
I am looking for an R docker image based on Fedora and Arch Linux. I found in this repo it has a Fedora-based docker image, and an Arch Linux in a PR (#41). Unfortunately, I couldn't find a `release` version of the Fedora one. Is there any reason why? I checked the other Fedora docker image also in this repo, but it doesn't have R inside (see my previous finding).

Thanks :)

**Comment by gaborcsardi** [comment]
> But, when I tried the devel and patched one, they don't have R inside it

R is in `/opt`

**Comment by ismailsunni** [comment]
Hi @gaborcsardi 

Thanks for the quick answer :)

What about my 2nd question, regarding the R release version on Fedora?

**Comment by gaborcsardi** [comment]
We mostly follow https://cran.r-project.org/web/checks/check_flavors.html and that has no R release on Fedora. But installing R release on Fedora is easy I guess, so you can make an image easily.

**Comment by ismailsunni** [comment]
Hi @gaborcsardi 
Ah, I see, now I understand. It seems it's better for me to create a new docker image for my purpose. Thanks for the answers :)
