### ISSUE TITLE
debian-gcc-devel image on DockerHub might be stale

### ISSUE THREAD

**Issue by thisisnic** [r-hub/rhub-linux-builders#55]
I'm running a CI job which depends on `debian-gcc-devel` and it's failing with this error:

`#8 1.563 E: Repository 'http://deb.debian.org/debian testing InRelease' changed its 'Codename' value from 'bullseye' to 'bookworm'`

I think it's due to a stale image on DockerHub, after Debian released `bullseye` as stable a few days ago.

Here's a reproducible example:

```
# run image with a terminal
docker run -it rhub/debian-gcc-devel:latest /bin/bash

# code which causes it to error
apt-get update && apt-get install -y libcurl4-openssl-dev
```

**Comment by gaborcsardi** [comment]
Thanks! GHA stopped the scheduled update.... try again pls.

**Comment by thisisnic** [comment]
Looking good now, thanks! :)

**Comment by nealrichardson** [comment]
@gaborcsardi would it be possible to do the same for the lto image? https://hub.docker.com/r/rhub/debian-gcc-devel-lto shows it hasn't been updated in 6 months and is now showing the same bookworm message.

**Comment by gaborcsardi** [comment]
@nealrichardson I have no clue why that was not in the GHA workflow. I added it and triggered a new build. If successful, it will be updated in about 30 minutes.

EDIT: looks good.
